version: "3.8"

services:
  localstack:
    container_name: "example-localstack"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - s3demo
  flask:
    container_name: flaskdemo
    build: .
    ports:
      - "5000:5000"
    networks:
      - s3demo
networks:
  s3demo:
    name: s3demo